// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqqbgjZxMqqz_YAlR-LpsWi4BkDrub7PY',
    appId: '1:965452038916:web:ffe510a18cea46058a4651',
    messagingSenderId: '965452038916',
    projectId: 'lmfao-2edf6',
    authDomain: 'lmfao-2edf6.firebaseapp.com',
    storageBucket: 'lmfao-2edf6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMUez3KmQi-kAYMXNM2B175GIDCDUZv8A',
    appId: '1:965452038916:android:bf44a27aef3e6cd78a4651',
    messagingSenderId: '965452038916',
    projectId: 'lmfao-2edf6',
    storageBucket: 'lmfao-2edf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9o3cBdfrdGgJf0TEy3c-J-prBB9QHYk',
    appId: '1:965452038916:ios:bd76f6b17c763eb58a4651',
    messagingSenderId: '965452038916',
    projectId: 'lmfao-2edf6',
    storageBucket: 'lmfao-2edf6.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqqbgjZxMqqz_YAlR-LpsWi4BkDrub7PY',
    appId: '1:965452038916:web:24cb5ff03cbe3ef28a4651',
    messagingSenderId: '965452038916',
    projectId: 'lmfao-2edf6',
    authDomain: 'lmfao-2edf6.firebaseapp.com',
    storageBucket: 'lmfao-2edf6.firebasestorage.app',
  );
}
